;
CREATE USER IF NOT EXISTS "SA" SALT '909d9f2365eb0085' HASH '302724bc731c80a6ca8ec5084c1eaf2d7a2d650cac5ca60d7fad0eb67af1649f' ADMIN;         
CREATE SEQUENCE "PUBLIC"."DRONES_SEQ" START WITH 1 INCREMENT BY 50;           
CREATE SEQUENCE "PUBLIC"."LOGS_SEQ" START WITH 1 INCREMENT BY 50;             
CREATE SEQUENCE "PUBLIC"."MEDICATIONS_SEQ" START WITH 1 INCREMENT BY 50;      
CREATE MEMORY TABLE "PUBLIC"."DRONES"(
    "DRONEID" BIGINT NOT NULL,
    "BATTERY_LEVEL" INTEGER NOT NULL,
    "MODEL" SMALLINT NOT NULL,
    "SERIAL_NUMBER" CHARACTER VARYING(100),
    "STATE" SMALLINT NOT NULL,
    "WEIGHT" FLOAT(24) NOT NULL
);               
ALTER TABLE "PUBLIC"."DRONES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_78B" PRIMARY KEY("DRONEID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DRONES;  
CREATE MEMORY TABLE "PUBLIC"."LOGS"(
    "ID" BIGINT NOT NULL,
    "CREATION_DATE_TIME" TIMESTAMP(6),
    "MESSAGE" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."LOGS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LOGS;    
CREATE MEMORY TABLE "PUBLIC"."MEDICATIONS"(
    "MEDID" BIGINT NOT NULL,
    "CODE" CHARACTER VARYING(255),
    "IMAGE" BINARY VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "WEIGHT" FLOAT(24) NOT NULL,
    "DRONEID" BIGINT NOT NULL
);      
ALTER TABLE "PUBLIC"."MEDICATIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("MEDID");               
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEDICATIONS;             
ALTER TABLE "PUBLIC"."DRONES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_78" CHECK("WEIGHT" <= CAST(500.0 AS DOUBLE PRECISION)) NOCHECK;             
ALTER TABLE "PUBLIC"."DRONES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" CHECK("BATTERY_LEVEL" <= 100) NOCHECK;   
ALTER TABLE "PUBLIC"."MEDICATIONS" ADD CONSTRAINT "PUBLIC"."UK_QL2UBNMOXYC4XIP8HFYPISAQ8" UNIQUE("CODE");     
ALTER TABLE "PUBLIC"."DRONES" ADD CONSTRAINT "PUBLIC"."UK_LSJVI6H63GA5X3QWVO5VOQ1F8" UNIQUE("SERIAL_NUMBER"); 
ALTER TABLE "PUBLIC"."MEDICATIONS" ADD CONSTRAINT "PUBLIC"."FK3U2HA67OUK284SNHVO2DMPXA2" FOREIGN KEY("DRONEID") REFERENCES "PUBLIC"."DRONES"("DRONEID") NOCHECK;              
